export const LOAD_NOTES_REQUEST = "LOAD_NOTES_REQUEST";
export const LOAD_NOTES_SUCCESS = "LOAD_NOTES_SUCCESS";
export const LOAD_NOTES_FAIL = "LOAD_NOTES_FAIL";

export const LOAD_NOTE_REQUEST = "LOAD_NOTE_REQUEST";
export const LOAD_NOTE_SUCCESS = "LOAD_NOTE_SUCCESS";
export const LOAD_NOTE_FAIL = "LOAD_NOTE_FAIL";

export const CREATE_NOTES_REQUEST = "CREATE_NOTES_REQUEST";
export const CREATE_NOTES_SUCCESS = "CREATE_NOTES_SUCCESS";
export const CREATE_NOTES_FAIL = "CREATE_NOTES_FAIL";
export const CREATE_NOTES_CLEAR = "CREATE_NOTES_CLEAR";

export const EDIT_NOTES_REQUEST = "EDIT_NOTES_REQUEST";
export const EDIT_NOTES_SUCCESS = "EDIT_NOTES_SUCCESS";
export const EDIT_NOTES_FAIL = "EDIT_NOTES_FAIL";
export const EDIT_NOTES_CLEAR = "EDIT_NOTES_CLEAR";

export const DELETE_NOTES_REQUEST = "DELETE_NOTES_REQUEST";
export const DELETE_NOTES_SUCCESS = "DELETE_NOTES_SUCCESS";
export const DELETE_NOTES_FAIL = "DELETE_NOTES_FAIL";
export const DELETE_NOTES_CLEAR = "DELETE_NOTES_CLEAR";

export const PIN_NOTES_REQUEST = "PIN_NOTES_REQUEST";
export const PIN_NOTES_SUCCESS = "PIN_NOTES_SUCCESS";
export const PIN_NOTES_FAIL = "PIN_NOTES_FAIL";
