export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const UPDATE_LOCAL_USER_DATA = " UPDATE_LOCAL_USER_DATA";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const CLEAR_REGISTER_DATA = "CLEAR_REGISTER_DATA";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";
export const UPDATE_USER_PROFILE_CLEAR = "UPDATE_USER_PROFILE_CLEAR";

export const UPDATE_USER_PASSWORD_REQUEST = "UPDATE_USER_PASSWORD_REQUEST";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
export const UPDATE_USER_PASSWORD_FAIL = "UPDATE_USER_PASSWORD_FAIL";
export const UPDATE_USER_PASSWORD_CLEAR = "UPDATE_USER_PASSWORD_CLEAR";

export const USER_VERIFICATIONCODE_REQUEST = "USER_VERIFICATIONCODE_REQUEST";
export const USER_VERIFICATIONCODE_SUCCESS = "USER_VERIFICATIONCODE_SUCCESS";
export const USER_VERIFICATIONCODE_FAIL = "USER_VERIFICATIONCODE_FAIL";

export const USER_VALIDATE_VC_REQUEST = "USER_VALIDATE_VC_REQUEST";
export const USER_VALIDATE_VC_SUCCESS = "USER_VALIDATE_VC_SUCCESS";
export const USER_VALIDATE_VC_FAIL = "USER_VALIDATE_VC_FAIL";

export const USER_RESET_PASS_REQUEST = "USER_RESET_PASS_REQUEST";
export const USER_RESET_PASS_SUCCESS = "USER_RESET_PASS_SUCCESS";
export const USER_RESET_PASS_FAIL = "USER_RESET_PASS_FAIL";
